name: environment setup
on:
  push:
    branches:
      - master

jobs:
  no-cache:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
      - name: check setup
        run: |
          node --version
          npm --version
      - name: install dependencies
        run: |
          yarn install  --frozen-lockfile
